# should follow this template
model_type: "attention" # OR "lstm", "attention"
training:
  epochs: 10          # Increased to allow for more refinement after fixing the vocab bug
  batch_size: 64      # Keep constant for comparison
  lr: 0.0004         # Lowered for more stable convergence
  weight_decay: 0.00001 # Small regularization to prevent overfitting

architecture:
  embed_size: 256     
  hidden_size: 512
  num_layers: 1
  dropout: 0.4        # Increased dropout to combat overfitting
