# should follow this template
model_type: "transformer" # OR "lstm", "attention"
training:
  epochs: 15          # Prob not modify if we do we should all have the same for all 3 models
  batch_size: 64      # Prob not modify if we do we should all have the same for all 3 models
  lr: 0.00005         # Can modify whatever
  # Any other training parameters added here will be IGNORED by train.py

architecture:
  embed_size: 512     # Prob not modify if we do we should all have the same for all 3 models
  #  ANYTHING HERE YOU CAN ADD ANY VARIABLE FOR YOUR MODEL TO TUNE THESE ARE JUST SOME EXAMPLES, U CAN ADD ANYTHING OR MODIFY
  # will  pass them to the Decoders and save them in the weights
  hidden_size: 512
  num_heads: 8
  num_layers: 6
  forward_expansion: 4
  dropout: 0.1